## **Purpose:**

Already equipped with information from the EDA phase, I can proceed to build a model, capable of predicting the crop yield using the feature data (within a slim margin of error).


To properly assess this problem I first have to define it.

- This is a regression problem, I'm trying to find an actual continuous value. Not some option in a category.

That said, I can approach this using several architectures:
- LinearRegression
- RandomForestRegressor
- DecisionTrees
- Ensemble Methods
- SVR
- GLM
- GPR
- Neural Nets


Normally, I'd select one of these and call it a night, once I get it working. But this time, I'll be building a model from each of all these architecture, the one that performs the best goes into the final production(to predict crop yield). But, the other models can be used for simpler tasks like (what temperature range should so and so crop be planted for this type of yield.)


Here's what I'm saying, I'll end up with one model to predict the crop yield given the features from the dataset. But I'll also make other models to answer questions, like what location would a crop give this sort of output giving these parameters... You dig?

In [1]:
import pandas as pd
import numpy as np

## **Final data preprocessing**

In [2]:
# Loaing the dataset
df= pd.read_csv('../../data/processed/Final_dataset.csv')

In [3]:
df.head()

,area,year,average_rain_fall_mm_per_year,crops,crop_yields,pesticide_tonnes,avg_temp
0,Albania,1990,1485.0,Maize,36613,121.0,16.37
1,Albania,1990,1485.0,Potatoes,66667,121.0,16.37
2,Albania,1990,1485.0,"Rice, paddy",23333,121.0,16.37
3,Albania,1990,1485.0,Sorghum,12500,121.0,16.37
4,Albania,1990,1485.0,Soybeans,7000,121.0,16.37

In [4]:
df.shape

(28242, 7)

We're firing on all cylinders here. Over 28,000 samples to train and test our model on. A smaller sample size than I'd prefer, but it would suffice.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28242 entries, 0 to 28241
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   area                           28242 non-null  object
 1   year                           28242 non-null  int64
 2   average_rain_fall_mm_per_year  28242 non-null  float64
 3   crops                          28242 non-null  object
 4   crop_yields                    28242 non-null  int64
 5   pesticide_tonnes               28242 non-null  float64
 6   avg_temp                       28242 non-null  float64
dtypes: float64(3), int64(2), object(2)
memory usage: 1.5+ MB

Seperating feature set from target variable

In [6]:
X = df.drop('crop_yields', axis = 1)
y= df['crop_yields']

**Feature Engineering**

So, the numerical features may not be perfect... lol, I already prepped them, but still, this is the right approach.

In [7]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [8]:
numeric_cols = ["year", "average_rain_fall_mm_per_year","pesticide_tonnes", "avg_temp"]

In [9]:
# if there are any missing values (which there aren't, thank you), SimpleImputer would fill 'em up with the median value
scaler = StandardScaler()
numeric_transformers = Pipeline(steps = [('imputer', SimpleImputer(strategy = 'median')),('scaler', scaler)])

Categorical data would need to be mapped. Regardless how many there are...

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
categorical_cols = ["area", "crops"]

In [12]:
categorical_transformer = Pipeline(steps = [('imputer', SimpleImputer(strategy = 'most_frequent')),('onehot', OneHotEncoder(handle_unknown = 'ignore', sparse_output = False))])

In [13]:
from sklearn.compose import ColumnTransformer
preprocessor = ColumnTransformer(transformers = [('num', numeric_transformers, numeric_cols), ('cat', categorical_transformer, categorical_cols)])

## **Split into training and testing data**

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test,y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42,)

In [16]:
X_train.head()

,area,year,average_rain_fall_mm_per_year,crops,pesticide_tonnes,avg_temp
5493,Cameroon,2005,1604.0,Sorghum,829.59,25.36
10969,India,1992,1083.0,Soybeans,70791.00,25.91
2001,Bahamas,1997,1292.0,Cassava,484.59,25.81
22157,Pakistan,1997,494.0,Potatoes,16936.00,23.76
311,Angola,2005,1010.0,Sweet potatoes,40.00,24.41

In [17]:
X_test.head()

,area,year,average_rain_fall_mm_per_year,crops,pesticide_tonnes,avg_temp
25564,Spain,2008,636.0,"Rice, paddy",40719.00,17.21
18113,Madagascar,1996,1513.0,Wheat,152.01,19.71
25607,Spain,2010,636.0,Sorghum,39043.00,16.51
6815,Colombia,2007,3240.0,Potatoes,82439.06,27.45
18144,Madagascar,2000,1513.0,Sweet potatoes,130.46,19.65

## **Model Building**

In [18]:
#Linear regression
from sklearn.linear_model import LinearRegression

linear_reg = LinearRegression()

In [19]:
# Ridge
from sklearn.linear_model import Ridge
ridge = Ridge()

In [20]:
# Lasso
from sklearn.linear_model import Lasso
lasso = Lasso()

In [21]:
# ElasticNet
from sklearn.linear_model import ElasticNet
e_net = ElasticNet()

In [22]:
# RandomForest
from sklearn.ensemble import RandomForestRegressor
rand_forest_reg = RandomForestRegressor()

In [23]:
# gradient Booster
from sklearn.ensemble import GradientBoostingRegressor
gradient_boost_reg = GradientBoostingRegressor()

In [24]:
# AdaBoostRegressor
from sklearn.ensemble import AdaBoostRegressor
ada_boost_reg  = AdaBoostRegressor()

In [25]:
# DecisionTreeregressor
from sklearn.tree import DecisionTreeRegressor
decision_reg = DecisionTreeRegressor()

In [26]:
# SVR
from sklearn.svm import SVR
svr = SVR()

In [27]:
# Kneighbors
from sklearn.neighbors import KNeighborsRegressor
knn_model = KNeighborsRegressor()

In [28]:
models = {"knn_model": knn_model, "svr_model": svr, "decision_trees_model": decision_reg, "AdaBoost_model":ada_boost_reg,"gradientBoost_Model": gradient_boost_reg,"random_forest_model":rand_forest_reg,"elastic_net_model":e_net,"lasso_model":lasso,"ridge_model":ridge,"linear_reg_model":linear_reg}

In [29]:
import sys,os
sys.path.append(os.path.abspath("../"))

In [31]:
from pipelines.evaluate_algorithms import algorithm_results
cv_comparison_df = algorithm_results(models, Pipeline, preprocessor, X_train, y_train)

print(cv_comparison_df)

Starting Cross-Validation (this may take a few minutes)...
Done: knn_model            | Mean R2: 0.9831 (+/- 0.0012)
Done: svr_model            | Mean R2: -0.2041 (+/- 0.0049)
Done: decision_trees_model | Mean R2: 0.9760 (+/- 0.0020)
Done: AdaBoost_model       | Mean R2: 0.5056 (+/- 0.0294)
Done: gradientBoost_Model  | Mean R2: 0.8725 (+/- 0.0061)
Done: random_forest_model  | Mean R2: 0.9859 (+/- 0.0016)
Done: elastic_net_model    | Mean R2: 0.2517 (+/- 0.0034)

c:\Users\mrtom\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.706e+10, tolerance: 1.304e+10
  model = cd_fast.enet_coordinate_descent(

Done: lasso_model          | Mean R2: 0.7531 (+/- 0.0110)
Done: ridge_model          | Mean R2: 0.7531 (+/- 0.0109)
Done: linear_reg_model     | Mean R2: 0.7531 (+/- 0.0110)

=== Robust Leaderboard (Cross-Validated) ===
              Algorithm  CV Mean R2  Consistency (Std Dev)
5   random_forest_model    0.985863               0.001601
0             knn_model    0.983146               0.001157
2  decision_trees_model    0.975989               0.002033
4   gradientBoost_Model    0.872465               0.006076
7           lasso_model    0.753093               0.011030
9      linear_reg_model    0.753091               0.011041
8           ridge_model    0.753081               0.010946
3        AdaBoost_model    0.505594               0.029409
6     elastic_net_model    0.251746               0.003406
1             svr_model   -0.204123               0.004916

Random Forest trumps in the rankings, so it would be the final model going into production

In [ ]:
import joblib

In [ ]:
final_model = Pipeline(steps=[("preprocessor", preprocessor), ("model",rand_forest_reg)])
final_model.fit(X_train,y_train)

joblib.dump(final_model,"../models/final-model.pkl")
joblib.dump(scaler, "../models/scaler-model.pkl")

['../models/scaler-model.pkl']

---------------------------------------------------------